title: Your Title
description: |
  Your description
baseurl: ''
url: ''
markdown: kramdown
facebook:
  app_id: null
logo: ../css/2016_style/img/icon-large.png
social:
  - title: facebook
    url: 'https://www.facebook.com'
  - title: twitter
    url: 'https://twitter.com'
google_site_verification: googleXXXXXXXXXXXXXXXX.html
include:
  - _2016_pages
  - _2017_pages
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
permalink: pretty
